Feature/update magma
0chain/bandwidth_marketplace pull request #3
Opened 2021-06-11 15:22 UTC by MurashovVen

- Magma is updated. Now [this](https://github.com/magma/augmented-networks) is used.
- Simplified Consumer.HSS verification procedure.
- Provider.AccessPoint service is silenced.

2021-06-16 08:27 UTC, platsko requested changes

2021-06-16 08:27 UTC, platsko commented on code/consumer/registration/const.go
> +func intLevelFromStr(level string) int {
I think name `logLevelFromStr` is better )

2021-06-16 08:27 UTC, platsko commented on code/magma/server/grpc/magma.go
> +	ctx, cancel := context.WithTimeout(ctx, 20*time.Second)
Timeout value - could it be moved to the config yaml file?

2021-06-16 08:27 UTC, platsko commented on code/magma/server/grpc/magma.go
> +	ctx, cancel := context.WithTimeout(ctx, 20*time.Second)
Timeout value - could it be moved to the config yaml file?

2021-06-16 08:27 UTC, platsko commented on code/provider/magma/client.go
> +// TODO remove or update accordance with magma
I think you can remove this file.

2021-06-16 08:27 UTC, platsko commented on code/provider/registration/const.go
> +func intLevelFromStr(level string) int {
`logLevelFromStr`

2021-06-16 08:27 UTC, platsko commented on code/provider/server/grpc/ap.go
>  }
I think you can remove this file.

2021-06-18 07:24 UTC, MurashovVen commented on code/consumer/registration/const.go
> +func intLevelFromStr(level string) int {
Renamed )

2021-06-18 07:24 UTC, MurashovVen commented on code/magma/server/grpc/magma.go
> +	ctx, cancel := context.WithTimeout(ctx, 20*time.Second)
Sure. I've moved timeouts to config.

2021-06-18 07:24 UTC, MurashovVen commented on code/magma/server/grpc/magma.go
> +	ctx, cancel := context.WithTimeout(ctx, 20*time.Second)
Sure. I've moved timeouts to config.

2021-06-18 07:24 UTC, MurashovVen commented on code/provider/magma/client.go
> +// TODO remove or update accordance with magma
Removed.

2021-06-18 07:24 UTC, MurashovVen commented on code/provider/registration/const.go
> +func intLevelFromStr(level string) int {
Renamed.

2021-06-18 07:24 UTC, MurashovVen commented on code/provider/server/grpc/ap.go
>  }
Removed.

2021-06-18 13:23 UTC, platsko approved these changes

2021-06-18 13:25 UTC, merged